import "./components/managePopup";
import "./components/scrollTop";
import "./components/videoModals";
import "./components/inputMask";
import "./components/sliders";
import "./components/customDate";
import "./components/programTabs";
import "./components/regForm";
import "./components/openModalLink";
import "./components/mainTabs";
import "./components/passPlaceholder";
import "./components/generateTemplate";
import "./components/accordions";
import "./components/burgerMenu";
import "./components/qrScanner";
import "./components/qrTurnstileScanner";
import "./components/qrRegScan";
import "./components/onPlaceReg";

