import './components/managePopup'
import './components/scrollTop'
import './components/videoModals'
import './components/inputMask'
import './components/sliders'
import './components/customDate'
import './components/programTabs'
import './components/succesReg'
import './components/regModal'
import './components/openModalLink'

